# Generated by Django 4.2.16 on 2024-11-10 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organizor',
            new_name='is_organizer',
        ),
    ]
