# Generated by Django 4.2.16 on 2024-11-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_rename_is_organizor_user_is_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_agents',
            new_name='is_agent',
        ),
    ]
